INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (1, 0, 'Apparels', 'Clothes, Garments, Dress');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (2, 1, 'Men Apparels', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (3, 1, 'Women Apparels', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (4, 1, 'Kids Apparels', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (5, 2, 'Men Arabic', 'Kaftans, kandora, dishdasha, agal, ghutra, shayla');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (6, 2, 'Men Formal', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (7, 2, 'Men Casual', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (8, 2, 'Men Underwear', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (9, 2, 'Men Dress Accessories', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (10, 3, 'Women Arabic', 'hijab, burkah, niqab, burqa, burka, al amira, shayla, Khimar, chador, abayas, kaftans, salwat suit, tunics');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (11, 3, 'Women Formal', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (12, 3, 'Women Casual', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (13, 3, 'Women Lingerie', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (14, 3, 'Women Dress Accessories', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (15, 4, 'School Uniform', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (16, 4, 'Boys Clothes', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (17, 4, 'Girls Clothes', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (18, 4, 'Kids Arabic', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (19, 4, 'Kids Accessiories', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (20, 0, 'Shoes', 'Footwear, Sandals, Slippers, Slipon, Flipflops, Shoes, Boots, Leather Shoes');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (21, 20, 'Men Shoes', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (22, 20, 'Women Shoes', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (23, 20, 'Kids Shoes', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (24, 21, 'Men Formal Shoes', 'Leather Shoes');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (25, 21, 'Men Casual Shoes', 'Sport shoes, sneakers, walking shoes, running shoes, gym shoes, fashion shoes');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (26, 21, 'Men Sandals', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (27, 21, 'Women Sandal', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (28, 21, 'Women Boots', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (29, 21, 'Women Casual Shoes', 'Sport shoes, sneakers, walking shoes, running shoes, gym shoes, fashion shoes');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (30, 21, 'Women Formal Shoes', 'Leather Shoes');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (31, 0, 'Watches', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (32, 31, 'Men Watches', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (33, 31, 'Women Watches', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (34, 31, 'Kid Watches', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (35, 32, 'Men Digital Watch', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (36, 32, 'Men Analogue Watch', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (37, 32, 'Men Smart Watch', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (38, 33, 'Women Analogue Watch', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (39, 33, 'Women Digital Watch', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (40, 33, 'Women Smart Watch', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (41, 0, 'Perfumes', 'Attar, Fragrance, Deodarant');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (42, 41, 'Men Perfumes', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (43, 41, 'Women Perfumes', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (44, 0, 'Jewellery', 'Earrings, Bracelets, Necklace, Anklet, Diamonds, Gold, Silver');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (45, 44, 'Earrings', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (46, 44, 'Bracelets', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (47, 44, 'Necklace', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (48, 44, 'Rings', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (49, 44, 'Anklet', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (50, 0, 'Beauty Products', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (51, 50, 'Men Beauty', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (52, 50, 'Women Beauty', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (53, 50, 'Kids Beauty', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (54, 50, 'Bath & Body', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (55, 50, 'Dental Care', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (56, 51, 'Men Grooming', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (57, 51, 'Men Skin', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (58, 51, 'Men Hair ', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (59, 52, 'Women Skin', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (60, 52, 'Women Hair', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (61, 52, 'Women Lipsticks', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (62, 52, 'Women Nailpaints', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (63, 52, 'Women Makeup', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (64, 0, 'Bags Wallets Luggage', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (65, 55, 'Kids Bags', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (66, 55, 'Luggage', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (67, 55, 'Women Bags', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (68, 55, 'Women Wallets', 'Purse, Clutches');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (69, 55, 'Men Bags', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (70, 55, 'Men Wallets', 'Purse, Clutches');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (71, 55, 'Men Briefcase', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (72, 0, 'Electronics and Appliances', 'Home appliance, Electrical appliances');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (73, 72, 'Laptops', 'computers, notepad, notebook');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (74, 72, 'TV', 'Plasma TV, LED TV, 4K TV, OLED TV, Television');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (75, 72, 'Music System', 'home theatre, speakers, mics, microphones, bluethoot speakers, subwoofer, woofer');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (76, 72, 'Headphones Earphones', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (77, 72, 'Microwave', 'microwave oven, oven');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (78, 72, 'Cooking Range', 'Gas stove, gas burner, gas over, induction tops, electric stove, electric cooker, oven, convection oven');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (79, 72, 'Refrigirator', 'Fridge, Freezer');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (80, 72, 'Cables', 'wires');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (81, 72, 'Wifi Devices', 'routers, modem');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (82, 72, 'Washing Machine', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (83, 72, 'Mobile Phones', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (84, 72, 'Wired Phones', 'landline, cellular phone, homeline');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (85, 72, 'Vaccum Cleaner', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (86, 72, 'Light Bulbs and Fans', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (87, 0, 'Books', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (88, 0, 'Stationeries', ' ');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (89, 0, 'Grocery', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (90, 89, 'Chocolates', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (91, 89, 'Milk & Cheese', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (92, 89, 'Meat', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (93, 89, 'Cooking Ingredients', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (94, 89, 'Coffee, Tea & Beverages', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (95, 0, 'Toys & Games', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (96, 0, 'Gifts, Souvenirs, Novelty', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (97, 0, 'Wellness & Sports', 'Gym equipments, sports racquets, tennis rackets, cricket bat, balls, football, basketball, baseball, dumbbells');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (98, 0, 'Eyewares', 'Opticals, Sunglasses, ');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (99, 0, 'Toys & Entertainments', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (100, 0, 'Alcohol', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (101, 0, 'Health Product', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (102, 0, 'Nutritional Supplements', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (103, 0, 'Home & Furniture', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (104, 103, 'Kitchen furniture', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (105, 103, 'Living room furniture', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (106, 103, 'Bathroom furniture', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (107, 103, 'Rugs & Carpets', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (108, 103, 'Artefacts', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (109, 103, 'Bedroom', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (110, 0, 'Supermarket', '');
INSERT INTO T_CATEGORY (id, parentId, name, synonyms) VALUES (111, 0, 'Restaurant', '');