INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (1, 'Adidas', 1, 0);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (2, 'Huawei', 2, 0);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (3, 'Nike', 3, 0);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (4, 'Oppo', 4, 0);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (5, 'Apple', 5, 0);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (6, 'Toyota', 6, 0);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (7, 'Cucci', 7, 0);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (8, 'Pandora', 8, 0);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (9, 'Bulgari', 9, 0);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (10, 'Rolex', 10, 0);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (11, 'Abu Dhabi Mall', 1, 1);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (12, 'Dubai Mall', 2, 1);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (13, 'WTC Mall ', 3, 1);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (14, 'Mushrif Mall', 4, 1);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (15, 'Yas Mall', 5, 1);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (16, 'IBN Battuta', 6, 1);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (17, 'Dubai Outlet', 7, 1);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (18, 'Dubai Marina', 8, 1);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (19, 'Mercato Mall', 9, 1);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (20, 'The Galleria', 10, 1);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (21, 'mobile phone', 1, 2);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (22, 'shoes', 2, 2);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (23, 'T-shirt', 3, 2);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (24, 'watches', 4, 2);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (25, 'computer', 5, 2);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (26, 'skirt', 6, 2);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (27, 'basketball', 7, 2);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (28, 'books', 8, 2);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (29, 'sunglass', 9, 2);
INSERT INTO T_POPULAR_SEARCH (id, name, score, searchType) VALUES (30, 'slippers', 10, 2);