INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (4, 9907, 1, null, 'discount_9907_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (5, 9907, 2, null, 'discount_9907_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (6, 9907, 3, null, 'discount_9907_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (7, 9908, 1, null, 'discount_9908_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (8, 9908, 2, null, 'discount_9908_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (9, 9908, 3, null, 'discount_9908_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (10, 9909, 1, null, 'discount_9909_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (11, 9909, 2, null, 'discount_9909_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (12, 9909, 3, null, 'discount_9909_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (13, 9910, 1, null, 'discount_9910_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (14, 9910, 2, null, 'discount_9910_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (15, 9910, 3, null, 'discount_9910_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (16, 9910, 4, null, 'discount_9910_4.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (17, 9911, 1, null, 'discount_9911_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (18, 9911, 2, null, 'discount_9911_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (19, 9912, 1, null, 'discount_9912_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (20, 9912, 2, null, 'discount_9912_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (21, 9913, 1, null, 'discount_9913_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (22, 9913, 2, null, 'discount_9913_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (23, 9914, 1, null, 'discount_9914_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (24, 9915, 1, null, 'discount_9915_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (25, 9915, 2, null, 'discount_9915_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (26, 9916, 1, null, 'discount_9916_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (27, 9916, 2, null, 'discount_9916_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (28, 9916, 3, null, 'discount_9916_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (29, 9916, 4, null, 'discount_9916_4.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (30, 9916, 5, null, 'discount_9916_5.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (31, 9917, 1, null, 'discount_9917_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (32, 9918, 1, null, 'discount_9918_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (33, 9919, 1, null, 'discount_9919_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (34, 9920, 1, null, 'discount_9920_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (35, 9921, 1, null, 'discount_9921_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (36, 9922, 1, null, 'discount_9922_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (37, 9923, 1, null, 'discount_9923_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (38, 9923, 2, null, 'discount_9923_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (39, 9924, 1, null, 'discount_9924_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (40, 9924, 2, null, 'discount_9924_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (41, 9924, 3, null, 'discount_9924_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (42, 9925, 1, null, 'discount_9925_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (43, 9925, 2, null, 'discount_9925_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (44, 9925, 3, null, 'discount_9925_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (45, 9927, 1, null, 'discount_9927_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (46, 9927, 2, null, 'discount_9927_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (47, 9927, 3, null, 'discount_9927_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (48, 9928, 1, null, 'discount_9928_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (49, 9928, 2, null, 'discount_9928_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (50, 9929, 1, null, 'discount_9929_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (51, 9929, 2, null, 'discount_9929_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (52, 9929, 3, null, 'discount_9929_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (53, 9930, 1, null, 'discount_9930_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (54, 9930, 2, null, 'discount_9930_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (55, 9930, 3, null, 'discount_9930_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (56, 9932, 1, null, 'discount_9932_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (57, 9932, 2, null, 'discount_9932_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (58, 9933, 1, null, 'discount_9933_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (59, 9933, 2, null, 'discount_9933_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (60, 9933, 3, null, 'discount_9933_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (61, 9934, 1, null, 'discount_9934_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (62, 9934, 2, null, 'discount_9934_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (63, 9934, 3, null, 'discount_9934_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (64, 9935, 1, null, 'discount_9935_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (65, 9935, 2, null, 'discount_9935_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (66, 9935, 3, null, 'discount_9935_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (67, 9936, 1, null, 'discount_9936_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (68, 9936, 2, null, 'discount_9936_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (69, 9937, 1, null, 'discount_9937_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (70, 9937, 2, null, 'discount_9937_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (71, 9937, 3, null, 'discount_9937_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (72, 9938, 1, null, 'discount_9938_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (73, 9938, 2, null, 'discount_9938_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (74, 9939, 1, null, 'discount_9939_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (75, 9939, 2, null, 'discount_9939_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (76, 9939, 3, null, 'discount_9939_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (77, 9940, 1, null, 'discount_9940_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (78, 9940, 2, null, 'discount_9940_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (79, 9941, 1, null, 'discount_9941_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (80, 9941, 2, null, 'discount_9941_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (81, 9942, 1, null, 'discount_9942_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (82, 9942, 2, null, 'discount_9942_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (83, 9943, 1, null, 'discount_9943_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (84, 9943, 2, null, 'discount_9943_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (85, 9943, 3, null, 'discount_9943_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (86, 9944, 1, null, 'discount_9944_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (87, 9944, 2, null, 'discount_9944_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (88, 9944, 3, null, 'discount_9944_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (89, 9945, 1, null, 'discount_9945_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (90, 9945, 2, null, 'discount_9945_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (91, 9946, 1, null, 'discount_9946_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (92, 9947, 1, null, 'discount_9947_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (93, 9947, 2, null, 'discount_9947_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (94, 9948, 1, null, 'discount_9948_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (95, 9949, 1, null, 'discount_9949_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (96, 9949, 2, null, 'discount_9949_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (97, 9949, 3, null, 'discount_9949_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (98, 9950, 1, null, 'discount_9950_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (99, 9951, 1, null, 'discount_9951_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (100, 9952, 1, null, 'discount_9952_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (101, 9952, 2, null, 'discount_9952_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (102, 9952, 3, null, 'discount_9952_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (103, 9953, 1, null, 'discount_9953_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (104, 9953, 2, null, 'discount_9953_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (105, 9954, 1, null, 'discount_9954_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (106, 9954, 2, null, 'discount_9954_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (107, 9955, 1, null, 'discount_9955_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (108, 9957, 1, null, 'discount_9957_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (109, 9958, 1, null, 'discount_9958_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (110, 9958, 2, null, 'discount_9958_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (111, 9959, 1, null, 'discount_9959_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (112, 9959, 2, null, 'discount_9959_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (113, 9959, 3, null, 'discount_9959_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (114, 9960, 1, null, 'discount_9960_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (115, 9960, 2, null, 'discount_9960_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (116, 9961, 1, null, 'discount_9961_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (117, 9961, 2, null, 'discount_9961_2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (118, 9961, 3, null, 'discount_9961_3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (119, 9962, 1, null, 'discount_9962_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (120, 9963, 1, null, 'discount_9963_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (121, 9964, 1, null, 'discount_9964_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (122, 9965, 1, null, 'discount_9965_1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (123, 9, 2, null, 'IMG_1837.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (124, 9, 1, null, 'IMG_1838.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (125, 9, 3, null, 'IMG_1839.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (126, 10, 1, null, 'IMG_1840.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (127, 10, 2, null, 'IMG_1841.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (128, 11, 1, null, 'IMG_1842.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (129, 11, 2, null, 'IMG_1843.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (130, 12, 2, null, 'IMG_1844.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (131, 12, 1, null, 'IMG_1845.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (132, 13, 1, null, 'IMG_1846.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (133, 13, 2, null, 'IMG_1847.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (134, 13, 3, null, 'IMG_1848.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (135, 13, 4, null, 'IMG_1849.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (136, 13, 5, null, 'IMG_1850.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (137, 14, 1, null, 'IMG_1851.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (138, 14, 2, null, 'IMG_1852.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (139, 14, 3, null, 'IMG_1853.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (140, 14, 4, null, 'IMG_1854.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (141, 15, 1, null, 'IMG_1855.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (142, 15, 2, null, 'IMG_1856.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (143, 16, 1, null, 'discount_16_1.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (144, 17, 2, null, 'IMG_1857.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (145, 17, 1, null, 'IMG_1858.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (146, 18, 1, null, 'IMG_1859.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (147, 18, 2, null, 'IMG_1860.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (148, 19, 1, null, 'IMG_1862.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (149, 19, 2, null, 'IMG_1863.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (150, 20, 1, null, 'IMG_1864.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (151, 20, 2, null, 'IMG_1865.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (152, 21, 1, null, 'IMG_1866.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (153, 21, 2, null, 'IMG_1867.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (154, 21, 3, null, 'IMG_1868.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (155, 22, 1, null, 'IMG_1869.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (156, 22, 2, null, 'IMG_1870.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (157, 23, 1, null, 'IMG_1871.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (158, 24, 1, null, 'IMG_1873.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (159, 24, 2, null, 'IMG_1874.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (160, 24, 3, null, 'IMG_1876.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (161, 25, 1, null, 'IMG_1877.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (162, 25, 2, null, 'IMG_1878.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (163, 26, 1, null, 'IMG_1879.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (164, 26, 2, null, 'IMG_1880.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (165, 27, 1, null, 'IMG_1881.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (166, 27, 2, null, 'IMG_1882.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (167, 28, 1, null, 'IMG_1883.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (168, 28, 2, null, 'IMG_1884.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (169, 28, 3, null, 'IMG_1885.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (170, 29, 1, null, 'IMG_1886.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (171, 30, 1, null, 'IMG_1887.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (172, 30, 2, null, 'IMG_1888.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (173, 30, 3, null, 'IMG_1889.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (174, 30, 4, null, 'IMG_1890.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (175, 31, 1, null, 'IMG_1891.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (176, 31, 2, null, 'IMG_1892.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (177, 31, 3, null, 'IMG_1893.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (178, 31, 4, null, 'IMG_1894.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (179, 32, 1, null, 'IMG_1895.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (180, 32, 2, null, 'IMG_1896.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (181, 32, 3, null, 'IMG_1897.png');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (182, 33, 1, null, '1476056330.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (183, 33, 2, null, '2080123805.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (184, 34, 1, null, '97740274.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (185, 35, 1, null, '548983390.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (186, 36, 1, null, '1997314729.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (187, 36, 2, null, '1271652855.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (188, 36, 3, null, '1853740435.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (189, 37, 1, null, '1894440945.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (190, 38, 1, null, '900275649.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (191, 39, 1, null, '57739919.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (192, 40, 1, null, '2066447996.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (193, 40, 2, null, '2042344059.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (194, 40, 3, null, '321338024.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (195, 40, 4, null, '1913393950.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (196, 41, 1, null, '1183275819.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (197, 41, 2, null, '752699572.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (198, 41, 3, null, '480630822.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (199, 41, 4, null, '1920279041.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (200, 42, 1, null, '1374830735.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (201, 43, 1, null, '803019423.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (202, 43, 2, null, '818379174.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (203, 44, 1, null, '1542490164.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (204, 45, 1, null, '2094251420.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (205, 45, 2, null, '1590764173.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (206, 46, 1, null, '1594945693.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (207, 47, 1, null, '1635880824.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (208, 48, 1, null, '1484792875.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (209, 48, 2, null, '973656436.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (210, 49, 1, null, '1757509473.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (211, 49, 2, null, '2100594613.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (212, 50, 1, null, '641075771.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (213, 51, 1, null, '259621178.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (214, 51, 2, null, '1958562057.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (215, 52, 1, null, '1066361673.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (216, 53, 1, null, '696213046.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (217, 54, 1, null, '2038540687.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (218, 54, 2, null, '1272870607.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (219, 55, 1, null, '199223653.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (220, 55, 2, null, '1268425215.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (221, 55, 3, null, '2019059622.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (222, 55, 4, null, '2001326997.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (223, 56, 1, null, '1745348355.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (224, 56, 2, null, '1738805326.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (225, 57, 1, null, '1852371699.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (226, 57, 2, null, '1789279137.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (227, 9966, 0, null, 'ZABKyZeEg9cIx4yOHSkEyKj9cOBxiuTz1qwdagoq0yaBeuwuJqra0DUKbgsW0QWk.jpeg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (228, 9966, 1, null, 'ggXWOH5grL4fKv7JRI5w2IO9EXBIf8UFJegaSZXw8Xf81ySfccT94aMVCpTIWAY0.jpeg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (229, 9966, 2, null, '3PeWRJgNdO6erBXlIlSKBq42SLsYTo5CrKNbcJOsTcuNJwCwDGQ0Wx8vo2GxeAqy.jpeg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (230, 9967, 0, null, 'QWlCs1aA5TozLYDnDjre7pLX8oNUVLvjPlbFJyQWcKQk6ko4Y8SmP5hJPvetKLfq.jpeg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (231, 9967, 1, null, 'HfWniWp0B0DoxKLW0gAY8AyjH4OINkCWzHCoxbRGIHxtIdbQgNBJko4NhBHVhNlW.jpeg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (232, 9967, 2, null, 'YagdYEjesZZsSrVA3QpI7hzAipHxNpq9mowrLkQQzOwDyP2flLiRXhdbAdCVyxtB.jpeg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (233, 9967, 3, null, 'w6RVTuZChJ257BvUNjyItENCTZJlWTsL7fZZ9dWMIPa0udXonA2zKjfaUkIwBEY5.jpeg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (234, 9967, 4, null, 'F5Q9RXcD1jKuQMzMINFyryqa8HM3q8j87f1gmcyVhNpIZdRDmyhX6NKbIO6ewVeb.jpeg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (235, 9967, 5, null, 'VDu3MxbbIX5LXFGdBvhFBAJQPZGp41H0OVJoqFfMnXOD6ri3S5bBsDtPYPxG5OgJ.jpeg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (236, 2, 1, null, '2 Microsoft Surface Pro 6-1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (237, 2, 2, null, '2 Microsoft Surface Pro 6-2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (238, 1, 1, null, '2 Microsoft Surface Pro 7-1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (239, 1, 2, null, '2 Microsoft Surface Pro 7-2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (240, 3, 1, null, '3 Mac Pro 1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (241, 3, 2, null, '3 Mac Pro 2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (242, 3, 3, null, '3 Mac Pro 3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (243, 4, 1, null, '4- Dell laptop 1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (244, 4, 2, null, '4- Dell laptop 2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (245, 4, 3, null, '4- Dell laptop 3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (246, 4, 4, null, '4- Dell laptop 4.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (247, 5, 1, null, '5 Samsung QLED 1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (248, 5, 2, null, '5 Samsung QLED 2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (249, 5, 3, null, '5 Samsung QLED 3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (250, 5, 4, null, '5 Samsung QLED 4.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (251, 5, 5, null, '5 Samsung QLED 5.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (252, 6, 1, null, '6 Hisense 4K TV 1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (253, 6, 2, null, '6 Hisense 4K TV 2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (254, 6, 3, null, '6 Hisense 4K TV 3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (255, 6, 4, null, '6 Hisense 4K TV 4.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (256, 6, 5, null, '6 Hisense 4K TV 5.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (257, 7, 1, null, '7 Philips UHD 4K 1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (258, 7, 2, null, '7 Philips UHD 4K 2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (259, 7, 3, null, '7 Philips UHD 4K 3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (260, 8, 1, null, '8 Philips OLED 1.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (261, 8, 2, null, '8 Philips OLED 2.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (262, 8, 3, null, '8 Philips OLED 3.jpg');
INSERT INTO T_DISCOUNT_IMAGE (id, discountId, orderIndex, title, imageName) VALUES (263, 8, 4, null, '8 Philips OLED 4.jpg');