INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (1, 'AF', 'Afghanistan', 'AFN', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (2, 'AX', 'Aland Islands', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (3, 'AL', 'Albania', 'ALL', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (4, 'DZ', 'Algeria', 'DZD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (5, 'AS', 'American Samoa', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (6, 'AD', 'Andorra', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (7, 'AO', 'Angola', 'AOA', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (8, 'AI', 'Anguilla', 'XCD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (9, 'AQ', 'Antarctica', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (10, 'AG', 'Antigua and Barbuda', 'XCD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (11, 'AR', 'Argentina', 'ARS', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (12, 'AM', 'Armenia', 'AMD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (13, 'AW', 'Aruba', 'AWG', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (14, 'AU', 'Australia', 'AUD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (15, 'AT', 'Austria', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (16, 'AZ', 'Azerbaijan', 'AZN', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (17, 'BS', 'Bahamas', 'BSD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (18, 'BH', 'Bahrain', 'BHD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (19, 'BD', 'Bangladesh', 'BDT', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (20, 'BB', 'Barbados', 'BBD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (21, 'BY', 'Belarus', 'BYR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (22, 'BE', 'Belgium', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (23, 'BZ', 'Belize', 'BZD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (24, 'BJ', 'Benin', 'XOF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (25, 'BM', 'Bermuda', 'BMD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (26, 'BT', 'Bhutan', 'BTN', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (27, 'BO', 'Bolivia', 'BOB', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (28, 'BQ', 'Bonaire', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (29, 'BA', 'Bosnia and Herzegovina', 'BAM', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (30, 'BW', 'Botswana', 'BWP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (31, 'BV', 'Bouvet Island', 'NOK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (32, 'BR', 'Brazil', 'BRL', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (33, 'IO', 'British Indian Ocean Territory', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (34, 'BN', 'Brunei', 'BND', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (35, 'BG', 'Bulgaria', 'BGN', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (36, 'BF', 'Burkina Faso', 'XOF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (37, 'BI', 'Burundi', 'BIF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (38, 'KH', 'Cambodia', 'KHR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (39, 'CM', 'Cameroon', 'XAF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (40, 'CA', 'Canada', 'CAD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (41, 'CV', 'Cabo Verde', 'CVE', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (42, 'KY', 'Cayman Islands', 'KYD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (43, 'CF', 'Central African Republic', 'XAF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (44, 'TD', 'Chad', 'XAF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (45, 'CL', 'Chile', 'CLP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (46, 'CN', 'China', 'CNY', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (47, 'CX', 'Christmas Island', 'AUD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (48, 'CC', 'Cocos Islands', 'AUD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (49, 'CO', 'Colombia', 'COP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (50, 'KM', 'Comoros', 'KMF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (51, 'CG', 'Republic of the Congo', 'XAF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (52, 'CD', 'Congo, the Democratic Republic', 'CDF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (53, 'CK', 'Cook Islands', 'NZD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (54, 'CR', 'Costa Rica', 'CRC', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (55, 'CI', 'Côte d’Ivoire', 'XOF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (56, 'HR', 'Croatia', 'HRK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (57, 'CU', 'Cuba', 'CUC', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (58, 'CW', 'Curaçao', 'ANG', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (59, 'CY', 'Cyprus', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (60, 'CZ', 'Czech Republic', 'CZK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (61, 'DK', 'Denmark', 'DKK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (62, 'DJ', 'Djibouti', 'DJF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (63, 'DM', 'Dominica', 'XCD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (64, 'DO', 'Dominican Republic', 'DOP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (65, 'EC', 'Ecuador', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (66, 'EG', 'Egypt', 'EGP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (67, 'SV', 'El Salvador', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (68, 'GQ', 'Equatorial Guinea', 'XAF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (69, 'ER', 'Eritrea', 'ERN', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (70, 'EE', 'Estonia', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (71, 'ET', 'Ethiopia', 'ETB', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (72, 'FK', 'Falkland Islands', 'FKP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (73, 'FO', 'Faroe Islands', 'DKK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (74, 'FJ', 'Fiji', 'FJD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (75, 'FI', 'Finland', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (76, 'FR', 'France', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (77, 'GF', 'French Guiana', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (78, 'PF', 'French Polynesia', 'XPF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (79, 'TF', 'French Southern Territories', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (80, 'GA', 'Gabon', 'XAF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (81, 'GM', 'Gambia', 'GMD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (82, 'GE', 'Georgia', 'GEL', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (83, 'DE', 'Germany', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (84, 'GH', 'Ghana', 'GHS', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (85, 'GI', 'Gibraltar', 'GIP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (86, 'GR', 'Greece', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (87, 'GL', 'Greenland', 'DKK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (88, 'GD', 'Grenada', 'XCD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (89, 'GP', 'Guadeloupe', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (90, 'GU', 'Guam', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (91, 'GT', 'Guatemala', 'GTQ', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (92, 'GG', 'Guernsey', 'GBP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (93, 'GN', 'Guinea', 'GNF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (94, 'GW', 'Guinea-Bissau', 'XOF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (95, 'GY', 'Guyana', 'GYD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (96, 'HT', 'Haiti', 'HTG', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (97, 'HM', 'Heard Island and McDonald Islands', 'AUD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (98, 'VA', 'Vatican City', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (99, 'HN', 'Honduras', 'HNL', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (100, 'HK', 'Hong Kong', 'HKD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (101, 'HU', 'Hungary', 'HUF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (102, 'IS', 'Iceland', 'ISK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (103, 'IN', 'India', 'INR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (104, 'ID', 'Indonesia', 'IDR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (105, 'IR', 'Iran', 'IRR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (106, 'IQ', 'Iraq', 'IQD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (107, 'IE', 'Ireland', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (108, 'IM', 'Isle of Man', 'GBP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (109, 'IL', 'Israel', 'ILS', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (110, 'IT', 'Italy', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (111, 'JM', 'Jamaica', 'JMD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (112, 'JP', 'Japan', 'JPY', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (113, 'JE', 'Jersey', 'GBP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (114, 'JO', 'Jordan', 'JOD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (115, 'KZ', 'Kazakhstan', 'KZT', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (116, 'KE', 'Kenya', 'KES', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (117, 'KI', 'Kiribati', 'AUD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (118, 'KP', 'North Korea', 'KPW', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (119, 'KR', 'South Korea', 'KRW', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (120, 'KW', 'Kuwait', 'KWD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (121, 'KG', 'Laos', 'LAK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (122, 'LA', 'Latvia', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (123, 'LB', 'Lebanon', 'LBP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (124, 'LS', 'Lesotho', 'LSL', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (125, 'LR', 'Liberia', 'LRD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (126, 'LY', 'Libya', 'LYD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (127, 'LI', 'Liechtenstein', 'CHF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (128, 'LU', 'Lithuania', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (129, 'MO', 'Macao', 'MOP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (130, 'MK', 'Macedonia', 'MKD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (131, 'MG', 'Madagascar', 'MGA', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (132, 'MW', 'Malawi', 'MWK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (133, 'MY', 'Malaysia', 'MYR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (134, 'MV', 'Maldives', 'MVR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (135, 'ML', 'Mali', 'XOF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (136, 'MT', 'Malta', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (137, 'MH', 'Marshall Islands', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (138, 'MQ', 'Martinique', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (139, 'MR', 'Mauritania', 'MRO', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (140, 'MU', 'Mauritius', 'MUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (141, 'YT', 'Mayotte', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (142, 'MX', 'Mexico', 'MXN', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (143, 'FM', 'Micronesia', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (144, 'MD', 'Moldova', 'MDL', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (145, 'MC', 'Monaco', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (146, 'MN', 'Mongolia', 'MNT', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (147, 'ME', 'Montenegro', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (148, 'MS', 'Montserrat', 'XCD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (149, 'MA', 'Morocco', 'MAD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (150, 'MZ', 'Mozambique', 'MZN', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (151, 'MM', 'Myanmar', 'MMK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (152, 'NA', 'Namibia', 'NAD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (153, 'NR', 'Nauru', 'AUD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (154, 'NP', 'Nepal', 'NPR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (155, 'NL', 'Netherlands', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (156, 'NC', 'New Caledonia', 'XPF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (157, 'NZ', 'New Zealand', 'NZD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (158, 'NI', 'Nicaragua', 'NIO', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (159, 'NE', 'Niger', 'XOF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (160, 'NG', 'Nigeria', 'NGN', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (161, 'NU', 'Niue', 'NZD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (162, 'NF', 'Norfolk Island', 'AUD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (163, 'MP', 'Northern Mariana Islands', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (164, 'NO', 'Norway', 'NOK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (165, 'OM', 'Oman', 'OMR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (166, 'PK', 'Pakistan', 'PKR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (167, 'PW', 'Palau', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (168, 'PS', 'Palestine', 'ILS', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (169, 'PA', 'Panama', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (170, 'PG', 'Papua New Guinea', 'PGK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (171, 'PY', 'Paraguay', 'PYG', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (172, 'PE', 'Peru', 'PEN', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (173, 'PH', 'Philippines', 'PHP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (174, 'PN', 'Pitcairn', 'NZD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (175, 'PL', 'Poland', 'PLN', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (176, 'PT', 'Portugal', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (177, 'PR', 'Puerto Rico', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (178, 'QA', 'Qatar', 'QAR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (179, 'RE', 'Reunion', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (180, 'RO', 'Romania', 'RON', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (181, 'RU', 'Russia', 'RUB', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (182, 'RW', 'Rwanda', 'RWF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (183, 'BL', 'Saint Barthelemy', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (184, 'SH', 'Saint Helena', 'SHP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (185, 'KN', 'Saint Kitts and Nevis', 'XCD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (186, 'LC', 'Saint Lucia', 'XCD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (187, 'MF', 'Saint Martin', 'ANG', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (188, 'PM', 'Saint Pierre and Miquelon', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (189, 'VC', 'Saint Vincent and the Grenadines', 'XCD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (190, 'WS', 'Samoa', 'WST', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (191, 'SM', 'San Marino', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (192, 'ST', 'Sao Tome and Principe', 'STD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (193, 'SA', 'Saudi Arabia', 'SAR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (194, 'SN', 'Senegal', 'XOF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (195, 'RS', 'Serbia', 'RSD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (196, 'SC', 'Seychelles', 'SCR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (197, 'SL', 'Sierra Leone', 'SLL', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (198, 'SG', 'Singapore', 'SGD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (199, 'SX', 'Sint Maarten', 'ANG', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (200, 'SK', 'Slovakia', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (201, 'SI', 'Slovenia', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (202, 'SB', 'Solomon Islands', 'SBD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (203, 'SO', 'Somalia', 'SOS', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (204, 'ZA', 'South Africa', 'ZAR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (205, 'GS', 'South Georgia', 'GBP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (206, 'SS', 'South Sudan', 'RUB', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (207, 'ES', 'Spain', 'EUR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (208, 'LK', 'Sri Lanka', 'LKR', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (209, 'SD', 'Sudan', 'SDG', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (210, 'SR', 'Suriname', 'SRD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (211, 'SJ', 'Svalbard and Jan Mayen', 'NOK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (212, 'SZ', 'Swaziland', 'SZL', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (213, 'SE', 'Sweden', 'SEK', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (214, 'CH', 'Switzerland', 'CHF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (215, 'SY', 'Syria', 'SYP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (216, 'TW', 'Taiwan', 'TWD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (217, 'TJ', 'Tajikistan', 'TJS', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (218, 'TZ', 'Tanzania', 'TZS', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (219, 'TH', 'Thailand', 'THB', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (220, 'TL', 'Timor-Leste', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (221, 'TG', 'Togo', 'XOF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (222, 'TK', 'Tokelau', 'NZD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (223, 'TO', 'Tonga', 'TOP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (224, 'TT', 'Trinidad and Tobago', 'TTD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (225, 'TN', 'Tunisia', 'TND', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (226, 'TR', 'Turkey', 'TRY', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (227, 'TM', 'Turkmenistan', 'TMT', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (228, 'TC', 'Turks and Caicos Islands', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (229, 'TV', 'Tuvalu', 'AUD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (230, 'UG', 'Uganda', 'UGX', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (231, 'UA', 'Ukraine', 'UAH', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (232, 'AE', 'United Arab Emirates', 'AED', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (233, 'GB', 'United Kingdom', 'GBP', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (234, 'US', 'United States', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (235, 'UM', 'United States Minor Outlying Islands', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (236, 'UY', 'Uruguay', 'UYU', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (237, 'UZ', 'Uzbekistan', 'UZS', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (238, 'VU', 'Vanuatu', 'VUV', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (239, 'VE', 'Venezuela', 'VEF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (240, 'VN', 'Vietnam', 'VND', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (241, 'VG', 'British Virgin Islands', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (242, 'VI', 'US Virgin Islands', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (243, 'WF', 'Wallis and Futuna', 'XPF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (244, 'EH', 'Western Sahara', 'MAD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (245, 'YE', 'Yemen', 'YER', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (246, 'ZM', 'Zambia', 'ZMW', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (247, 'ZW', 'Zimbabwe', 'USD', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (248, 'KG', 'Kyrgyzstan', 'KGS', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (249, 'LI', 'Lichtenstein', 'CHF', '01');
INSERT INTO T_COUNTRY (id, iso2, countryName, currency, phoneCode) VALUES (250, 'LU', 'Luxembourg', 'EUR', '01');