# This file will override the default one if run with: -Dspring.profiles.active=prod
spring:
  profiles:
    active: default

  datasource:
    url: jdbc:mysql://sale-explore.c3phboxdrnth.ap-southeast-1.rds.amazonaws.com:3306/saleexplore?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: api-server
    password: tsSbCqJbbKY3FX9t33Zz

  # REDIS (RedisProperties)
  redis:
    host: localhost # TODO. need a better the endpoint for the production redis server
    port: 6379
    timeout: 2000


logging:
  level:
    org:
      springframework:
        security: ERROR, WARN, INFO
    com:
      iiai:
        discountserver: ERROR, WARN, INFO


app:
  # some custom defined values
  serverBaseUrl: https://saleexplore.com:8443/
  promotionBaseUrl: https://saleexplore.com:9443/
  imageTaggerBaseUrl: http://10.0.0.85:8084/
  profaneImageFilterBaseUrl: http://10.0.0.85:8086/


  ios:
    pushCertificatePd: mTYKJBwAmD346duj
    pushCertificatePath: "secrets/apns_distribution.p12"

  debug: false
